//
//  AppIcon.swift
//  MovieStreamingApple
//
//  Centralized iconography for the app.
//

import Foundation

enum AppIcon {
    static let arrowClockwise = "arrow.clockwise"
    static let arrowCounterclockwise = "arrow.counterclockwise"
    static let arrowLeft = "arrow.left"
    static let arrowUpArrowDown = "arrow.up.arrow.down"
    static let arrowUpLeftAndArrowDownRight = "arrow.up.left.and.arrow.down.right"
    static let arrowUpRight = "arrow.up.right"
    static let backwardEndFill = "backward.end.fill"
    static let at = "at"
    static let bookmark = "bookmark"
    static let bookmarkFill = "bookmark.fill"
    static let building2 = "building.2"
    static let calendar = "calendar"
    static let camera = "camera"
    static let chartBarFill = "chart.bar.fill"
    static let chartLineUptrendXyaxis = "chart.line.uptrend.xyaxis"
    static let checkmark = "checkmark"
    static let chevronDown = "chevron.down"
    static let chevronLeft = "chevron.left"
    static let chevronRight = "chevron.right"
    static let chevronRightCircleFill = "chevron.right.circle.fill"
    static let chevronUp = "chevron.up"
    static let clock = "clock"
    static let exclamationmarkTriangle = "exclamationmark.triangle"
    static let exclamationmarkTriangleFill = "exclamationmark.triangle.fill"
    static let exclamationmarkShield = "exclamationmark.shield"
    static let eye = "eye"
    static let film = "film"
    static let filmFill = "film.fill"
    static let forwardEndFill = "forward.end.fill"
    static let forwardFill = "forward.fill"
    static let gearshape = "gearshape"
    static let globe = "globe"
    static let heart = "heart"
    static let house = "house"
    static let houseFill = "house.fill"
    static let infoCircleFill = "info.circle.fill"
    static let ipadLandscape = "ipad.landscape"
    static let gobackward10 = "gobackward.10"
    static let goforward10 = "goforward.10"
    static let line3HorizontalDecreaseCircle = "line.3.horizontal.decrease.circle"
    static let link = "link"
    static let listBulletBelowRectangle = "list.bullet.below.rectangle"
    static let listBulletRectanglePortrait = "list.bullet.rectangle.portrait"
    static let lockFill = "lock.fill"
    static let magnifyingglass = "magnifyingglass"
    static let mappinAndEllipse = "mappin.and.ellipse"
    static let megaphone = "megaphone"
    static let paintpaletteFill = "paintpalette.fill"
    static let person2 = "person.2"
    static let person2Fill = "person.2.fill"
    static let personFill = "person.fill"
    static let personCropCircleFill = "person.crop.circle.fill"
    static let person2Crop = "person.crop.circle.fill"
    static let photo = "photo"
    static let play = "play"
    static let playCircle = "play.circle"
    static let playCircleFill = "play.circle.fill"
    static let playFill = "play.fill"
    static let playRectangle = "play.rectangle"
    static let rectangleStackFill = "rectangle.stack.fill"
    static let playRectangleFill = "play.rectangle.fill"
    static let playSlash = "play.slash"
    static let sparkles = "sparkles"
    static let squareAndArrowUp = "square.and.arrow.up"
    static let star = "star"
    static let starFill = "star.fill"
    static let starLeadingHalfFilled = "star.leadinghalf.filled"
    static let tag = "tag"
    static let textBubble = "text.bubble"
    static let textPage = "text.page"
    static let trash = "trash"
    static let tv = "tv"
    static let xmark = "xmark"
    static let xmarkCircleFill = "xmark.circle.fill"

    // MARK: - Player Settings & Appearance
    static let gaugeNeedle = "gauge.with.dots.needle.bottom.50percent"
    static let sparklesTv = "sparkles.tv"
    static let captionsBubble = "captions.bubble"
    static let textformatAbc = "textformat.abc"
    static let serverRack = "server.rack"
    static let forwardFrame = "forward.frame"
    static let plus = "plus"
    static let handThumbsup = "hand.thumbsup"
    static let paperplane = "paperplane"
    static let checkmarkSeal = "checkmark.seal"
    static let photoOnRectangle = "photo.on.rectangle"
    static let rectanglePortrait = "rectangle.portrait"
    static let arrowUpRight2 = "arrow.up.right.square"

    // MARK: - Subtitle Appearance
    static let arrowUpAndDown = "arrow.up.and.down"
    static let textformatSize = "textformat.size"
    static let textformat = "textformat"
    static let bold = "bold"
    static let circleLefthalfFilled = "circle.lefthalf.filled"
    static let shadow = "shadow"

    // MARK: - Profile
    static let bellFill = "bell.fill"
    static let clockArrowCirclepath = "clock.arrow.circlepath"
    static let heartFill = "heart.fill"
    static let arrowDownCircleFill = "arrow.down.circle.fill"
}
